baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Hugo Hermit"
theme = "hermit"
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true
blackfriday = { }

[author]
name = "John Doe"

[taxonomies]
tag = "tags"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
themeColor = "#494f5c"
homeSubtitle = "A minimal and fast theme for Hugo."
footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
justifyContent = false
relatedPosts = false
code_copy_button = true

  [[params.social]]
  name = "twitter"
  url = "https://twitter.com/"

  [[params.social]]
  name = "instagram"
  url = "https://instagram.com/"

  [[params.social]]
  name = "github"
  url = "https://github.com/"

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "About"
url = "about-hugo/"
weight = 20
