backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: config
    label: Config
    files:
      - name: config
        label: Config
        file: config.toml
        fields:
          - widget: image
            name: logo
            label: Logo
            required: false
            hint: the path of the logo image
  - name: generic_page
    label: Generic Page Models
    folder: content/
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: false
      - widget: date
        name: date
        label: Date
        required: false
      - widget: hidden
        name: layout
        label: Layout
        required: true
        default: default
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: layout
      value: default
  - name: post
    label: Postss
    folder: content/posts
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: false
      - widget: date
        name: date
        label: Date
        required: false
      - widget: list
        name: tags
        label: Tags
        required: false
        field:
          label: String
          name: string
          widget: string
      - widget: boolean
        name: draft
        label: Draft
        required: false
      - widget: hidden
        name: layout
        label: Layout
        required: true
        default: posts
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: layout
      value: posts
